version: "3"

vars:
  GIT_COMMIT:
    sh: cd urfd-nng-dashboard && git rev-parse --short HEAD 2> /dev/null || echo "docker"
  GIT_VERSION:
    sh: cd urfd-nng-dashboard && git describe --tags --always --dirty --match "v*" 2> /dev/null | sed 's/-g\([0-9a-f]\{7,\}\)/-\1/' || echo "docker"

tasks:
  build:
    desc: Build Docker images with Git metadata
    cmds:
      - GIT_COMMIT="{{.GIT_COMMIT}}" GIT_VERSION="{{.GIT_VERSION}}" docker-compose build {{.CLI_ARGS}}

  up:
    desc: Start Docker containers
    cmds:
      - docker-compose up -d {{.CLI_ARGS}}

  down:
    desc: Stop Docker containers
    cmds:
      - docker-compose down

  logs:
    desc: View logs
    cmds:
      - docker-compose logs -f {{.CLI_ARGS}}
